# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: "Unit Test: web-based functions"

on:
  push:
    branches:
    - master
    - premerge
  pull_request:
    branches:
    - master
    - premerge
  schedule:
  # Web crawlers might be outdated because of website updating, so run periodically to follow the changes
  - cron: '9 9 * * 3,6,0'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      setup_rdp:
        type: boolean
        description: 'Connect to runner via remote desktop'
        required: false
        default: false
      use_proxy:
        type: boolean
        description: 'Use clash proxy for specific sites'
        required: false
        default: false

jobs:
  test-web-crawlers:

    runs-on: windows-latest
    env:
      PYTHONIOENCODING: "utf-8"
      PYTEST_ADDOPTS: "-rA --color=yes --tb=long --showlocals"

    steps:
    - uses: actions/checkout@v4

    - name: Setup Remote Desktop
      env:
        RDP_PASSWORD: ${{ secrets.RDP_PASSWORD }}
        CF_TUNNEL_TOKEN: ${{ secrets.CF_TUNNEL_TOKEN }}
      if: ${{ !cancelled() && github.event_name == 'workflow_dispatch' && inputs.setup_rdp }}
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "$env:RDP_PASSWORD" -Force)

        choco feature disable -n=showDownloadProgress
        choco install cloudflared
        Start-Process -FilePath "cloudflared" -ArgumentList "-f tunnel run --token $env:CF_TUNNEL_TOKEN"
        echo "Cloudflared tunnel started"

    - name: Setup Python 3.8
      uses: actions/setup-python@v5
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install -r requirements.txt

    - name: Setup clash proxy
      if: ${{ inputs.use_proxy }}
      env:
        CLASH_SUBSCRIPTION_URL: ${{ secrets.CLASH_SUBSCRIPTION_URL }}
      run: |
        Invoke-WebRequest -Uri "https://github.com/Kuingsmile/clash-core/releases/download/1.18/clash-windows-amd64-v3-v1.18.0.zip" -OutFile "clash.zip"
        Expand-Archive -Path "clash.zip"
        Invoke-WebRequest -Uri "$env:CLASH_SUBSCRIPTION_URL" -OutFile "clash\clash.yaml"
        Start-Process -FilePath "clash\clash-windows-amd64-v3.exe" -ArgumentList "-f clash\clash.yaml"
        $iniContent = Get-Content -Path "core\config.ini" -Raw
        $iniContent = $iniContent -replace "use_proxy = no", "use_proxy = yes"
        $iniContent = $iniContent -replace "auto_update = yes", "auto_update = no"
        $iniContent | Set-Content -Path "core\config.ini" -Encoding UTF8

    - name: Test web crawlers
      run: |
        chcp 65001
        pytest unittest/test_crawlers.py

    - name: Upload log as artifact
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: JavSP-web-funcs.log
        path: JavSP.log

    - name: Setup VS Code and wait RDP connection
      if: ${{ !cancelled() && github.event_name == 'workflow_dispatch' && inputs.setup_rdp }}
      run: |
        choco install vscode
        Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
        refreshenv
        code --install-extension ms-python.python
        code --wait --new-window .
